name: foss_warn
description: Eine FOSS Umsetzung von NINA
publish_to: 'none'
version: 0.5.1+27

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.6
  flutter_local_notifications: ^14.0.0+1
  shared_preferences: ^2.1.0
  shared_preferences_android: ^2.1.4
  provider: ^6.0.5
  rxdart: ^0.27.7
  url_launcher: ^6.1.10
  share_plus: ^6.3.4
  app_settings: ^4.2.0
  android_alarm_manager_plus: ^2.1.4
  intl: ^0.17.0 # for localizations
  unifiedpush: ^5.0.0

  # flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/app_icon.png"
  android: true
  ios: true

flutter:
  generate: true # for localizations
  uses-material-design: true
  assets:
   # welcome screen
   - assets/app_icon.png
   - assets/location.png
   - assets/battery.png
   - assets/check.png
   - assets/steps.png
   - assets/paragraph.png
